# Generated by Django 6.0.1 on 2026-03-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=15)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("shift", models.CharField(blank=True, max_length=20, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.CharField(max_length=150)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=50)),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="app/img/candidate"
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                (
                    "jobdescription",
                    models.CharField(blank=True, max_length=285, null=True),
                ),
                ("min_salary", models.BigIntegerField(blank=True, null=True)),
                ("max_salary", models.BigIntegerField(blank=True, null=True)),
                (
                    "highest_edu",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=150)),
                ("state", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("contact", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=150)),
                ("logo_pic", models.ImageField(upload_to="app/img/company")),
            ],
        ),
        migrations.CreateModel(
            name="UserMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("otp", models.IntegerField(blank=True, null=True)),
                ("role", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("salary", models.IntegerField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.candidate"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.job"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.usermaster"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.usermaster"
            ),
        ),
    ]
