# Generated by Django 6.0.1 on 2026-03-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
