# Generated by Django 6.0.1 on 2026-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_usermaster_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="max_salary",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="min_salary",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
