# Generated by Django 6.0.1 on 2026-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_candidate_dob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="description",
            new_name="job_description",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="title",
            new_name="job_title",
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
