# Generated by Django 6.0.1 on 2026-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_description_job_job_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
