# Generated by Django 6.0.1 on 2026-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_candidate_max_salary_candidate_min_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="highest_edu",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
