# Generated by Django 6.0.1 on 2026-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_candidate_highest_edu"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="experience",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
