# Generated by Django 6.0.1 on 2026-03-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_job_deadline_job_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
