# Generated by Django 6.0.1 on 2026-02-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_candidate_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
