# Generated by Django 6.0.1 on 2026-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_candidate_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="shift",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
