# Generated by Django 6.0.1 on 2026-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_candidate_jobdescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="app/img/candidate"
            ),
        ),
    ]
